# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Jain"
license = "MIT"
licenselink = "https://github.com/atishay/atishay.github.io/blob/master/LICENSE"
description = "Personal theme for websites"
homepage = "https://atishay.me"
tags = ["personal", "dark-mode"]
features = []
min_version = "0.55"

[author]
  name = "Atishay Jain"
  homepage = "https://atishay.me"
